# Generated by Django 4.0.3 on 2022-04-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('count_lessons', models.CharField(max_length=50)),
            ],
        ),
    ]
