# Generated by Django 4.0.3 on 2022-05-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_buissines_category_makala_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
